def MaxMap(freqMap):
    maxArray = [key for key, value in freqMap.items() if value == max(freqMap.values())]
    return maxArray

def FrequencyTable(Text, k):
    freqMap = {}
    n = len(Text)
    for i in range(n-k):
        Pattern = Text[i:i+k]
        if freqMap.get(Pattern) == None:
            freqMap[Pattern] = 1
        else:
            freqMap[Pattern] = freqMap[Pattern]+1
    return freqMap

def FrequentWords(Text, k):
    frequentPatterns = []
    freqMap = FrequencyTable(Text, k)
    maxArray = MaxMap(freqMap)
    for pattern in freqMap:
        if pattern in maxArray:
            frequentPatterns.append(pattern)
    return frequentPatterns


x = FrequencyTable('ACGTTGCATGTCGCATGATGCATGAGAGCT', 4)
x
MaxMap(x)
FrequentWords('TCCCTAGATCCCTAGAAGTCCGCCAAGCTGCTCCCTAGAAGTCCGCCAGTCCGCCTTGTAAATCCCTAGAAAGCTGCAGTCCGCCAAGCTGCAAGCTGCTCCCTAGAAGTCCGCCAAGCTGCTTGTAAATTGTAAAAAGCTGCCATGCGTCAAGTCCGCCTCCCTAGATTGTAAAAGTCCGCCCATGCGTCACATGCGTCATTGTAAACATGCGTCAAAGCTGCCATGCGTCACATGCGTCATCCCTAGACATGCGTCAAGTCCGCCAAGCTGCTCCCTAGACATGCGTCATTGTAAATCCCTAGACATGCGTCAAGTCCGCCAAGCTGCAAGCTGCTTGTAAAAAGCTGCAAGCTGCTTGTAAATCCCTAGACATGCGTCAAAGCTGCCATGCGTCAAGTCCGCCTTGTAAATCCCTAGAAGTCCGCCTCCCTAGATCCCTAGACATGCGTCAAGTCCGCCAGTCCGCCAAGCTGCAGTCCGCCAGTCCGCCTTGTAAAAGTCCGCCTTGTAAAAAGCTGCAGTCCGCCAAGCTGCTTGTAAAAAGCTGCTCCCTAGAAAGCTGCTTGTAAACATGCGTCACATGCGTCATTGTAAAAAGCTGCAAGCTGCAAGCTGCCATGCGTCAAAGCTGCTTGTAAAAGTCCGCCCATGCGTCAAGTCCGCCCATGCGTCACATGCGTCATCCCTAGATCCCTAGAAGTCCGCCTCCCTAGATTGTAAAAGTCCGCCAAGCTGCTCCCTAGACATGCGTCACATGCGTCAAAGCTGCTTGTAAAAAGCTGCTTGTAAATCCCTAGAAGTCCGCCTCCCTAGAAAGCTGCTCCCTAGAAAGCTGCTCCCTAGAAGTCCGCC', 14)